/**
 * One-off migration: Land Battles / Naval Battles / Amphibious Operations
 * coverage for Military Conflicts + new battle lemmas. Run update_all_data.js after.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const wordsPath = path.join(__dirname, "..", "data", "words.json");

const L = "Land Battles";
const N = "Naval Battles";
const A = "Amphibious Operations";

/** @type {Record<string, ('L'|'N'|'A')[]>} */
const classify = {
  "An Lushan Rebellion": ["L"],
  "Bar Kokhba Revolt": ["L"],
  "Battle of Actium": ["N"],
  "Battle of Agincourt": ["L"],
  "Battle of Alesia": ["L"],
  "Battle of Carrhae": ["L"],
  "Battle of Crécy": ["L"],
  "Battle of Dien Bien Phu": ["L"],
  "Battle of Hattin": ["L"],
  "Battle of Jutland": ["N"],
  "Battle of Lake Poyang": ["N"],
  "Battle of Lepanto": ["N"],
  "Battle of Pharsalus": ["L"],
  "Battle of Philippi": ["L"],
  "Battle of Poitiers": ["L"],
  "Battle of Red Cliff": ["N"],
  "Battle of Sluys": ["N"],
  "Battle of Trafalgar": ["N"],
  "Battle of Tumu Fortress": ["L"],
  "Battle of Yamen": ["N"],
  "Battle of Zhizhi": ["L"],
  "Bay of Pigs": ["A", "L", "N"],
  "Bay of Pigs Invasion": ["A", "L", "N"],
  "Bohemian Revolt": ["L"],
  "Chu–Han Contention": ["L"],
  "Dungan Revolt": ["L"],
  Gettysburg: ["L"],
  "Han Wudi's Defeat of the Xiongnu": ["L"],
  "Hussite Wars": ["L"],
  "Imjin War": ["L", "N"],
  "Jingkang Incident": ["L"],
  "Jingnan Campaign": ["L"],
  "Kitos War": ["L"],
  "Ming–Vietnam War": ["L"],
  "Mongol Conquest of China": ["L"],
  "Operation Overlord": ["L", "N", "A"],
  "Pickett's Charge": ["L"],
  "Red Turban Rebellion": ["L"],
  "Siege of Calais": ["L"],
  "Siege of Orléans": ["L"],
  "Siege of Suiyang": ["L"],
  "Soviet-Afghan War": ["L"],
  "The Algerian War": ["L"],
  "The American Civil War": ["L"],
  "The American Revolution": ["L", "A"],
  "The Battle of Stalingrad": ["L"],
  "The Boer War": ["L"],
  "The Boxer Rebellion": ["L"],
  "The Crimean War": ["L", "N"],
  "The Crusades": ["L"],
  "The Cuban Revolution": ["L"],
  "The English Civil War": ["L"],
  "The First Barons' War": ["L"],
  "The First Crusade": ["L"],
  "The Franco-Prussian War": ["L"],
  "The French Revolution": ["L"],
  "The Gulf War": ["L"],
  "The Haitian Revolution": ["L"],
  "The Hundred Days": ["L"],
  "The Hundred Years War": ["L", "N"],
  "The Iran-Iraq War": ["L"],
  "The Iraq War": ["L", "A"],
  "The Italian Wars": ["L", "N"],
  "The Korean War": ["L", "N", "A"],
  "The Mexican Revolution": ["L"],
  "The Napoleonic Wars": ["L", "N"],
  "The Russian Civil War": ["L"],
  "The Russian Invasion of Ukraine": ["L"],
  "The Russian Revolution": ["L"],
  "The Russo-Japanese War": ["L", "N"],
  "The Seven Years' War": ["L", "N"],
  "The Spanish Armada": ["N", "A"],
  "The Spanish Civil War": ["L"],
  "The Spanish-American War": ["L", "N", "A"],
  "The Syrian Civil War": ["L"],
  "The Thirty Years War": ["L"],
  "The Trojan War": ["L"],
  "The Vietnam War": ["L"],
  "The Yugoslav Wars": ["L"],
  Thermopylae: ["L"],
  "Third Servile War": ["L"],
  "World War I": ["L", "N"],
  "World War II": ["L", "N", "A"],
  "Yellow Turban Rebellion": ["L"],
};

const tagMap = { L, N, A };

/** New lemmas: categories only (Starts/Ends added by update_all_data.js) */
const newWords = {
  "Battle of Anzio": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things British",
    "Things German",
    "Things Italian",
    "World War II",
  ],
  "Battle of the Coral Sea": [
    "1940s",
    "20th Century",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Australian",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Guadalcanal": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Australian",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Inchon": [
    "1950s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "The Korean War",
    "Things American",
    "Things Korean",
  ],
  "Battle of Iwo Jima": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Leyte Gulf": [
    "1940s",
    "20th Century",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Filipino",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Manila Bay": [
    "1890s",
    "19th Century",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "The Spanish-American War",
    "Things American",
    "Things Spanish",
  ],
  "Battle of Midway": [
    "1940s",
    "20th Century",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Okinawa": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Peleliu": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Salamis": [
    "5th Century BC",
    "Ancient Times",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "Things Greek",
    "Things Persian",
  ],
  "Battle of Salerno": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things British",
    "Things German",
    "Things Italian",
    "World War II",
  ],
  "Battle of Saipan": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Santiago de Cuba": [
    "1890s",
    "19th Century",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "The Spanish-American War",
    "Things American",
    "Things Spanish",
  ],
  "Battle of Tarawa": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things Japanese",
    "World War II",
  ],
  "Battle of Tsushima": [
    "1900s",
    "20th Century",
    "Battles",
    "Events",
    "Military Conflicts",
    "Naval Battles",
    "The Russo-Japanese War",
    "Things Japanese",
    "Things Russian",
  ],
  "D-Day": [
    "1940s",
    "1944",
    "20th Century",
    "Battles",
    "D-Day",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things British",
    "Things Canadian",
    "Things French",
    "Things German",
    "World War II",
  ],
  "Gallipoli Campaign": [
    "1910s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things Australian",
    "Things British",
    "Things French",
    "Things Turkish",
    "World War I",
  ],
  "Invasion of Sicily": [
    "1940s",
    "20th Century",
    "Battles",
    "Amphibious Operations",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "Things American",
    "Things British",
    "Things German",
    "Things Italian",
    "World War II",
  ],
  "Siege of Sevastopol": [
    "1850s",
    "19th Century",
    "Battles",
    "Events",
    "Land Battles",
    "Military Conflicts",
    "Naval Battles",
    "The Crimean War",
    "Things British",
    "Things French",
    "Things Russian",
    "Things Turkish",
  ],
};

const words = JSON.parse(fs.readFileSync(wordsPath, "utf8"));

for (const [lemma, codes] of Object.entries(classify)) {
  if (!words[lemma]) {
    console.warn("Missing word (skipped):", lemma);
    continue;
  }
  const set = new Set(words[lemma]);
  for (const c of codes) set.add(tagMap[c]);
  words[lemma] = [...set].sort();
}

for (const [lemma, cats] of Object.entries(newWords)) {
  if (words[lemma]) {
    console.warn("Word already exists (merge):", lemma);
    const set = new Set([...words[lemma], ...cats]);
    words[lemma] = [...set].sort();
  } else {
    words[lemma] = [...cats].sort();
  }
}

const sorted = Object.keys(words)
  .sort((a, b) => a.localeCompare(b))
  .reduce((o, k) => {
    o[k] = words[k];
    return o;
  }, {});

fs.writeFileSync(wordsPath, JSON.stringify(sorted, null, 2), "utf8");
console.log("Wrote", wordsPath);
console.log("Classified", Object.keys(classify).length, "existing lemmas");
console.log("Added/merged", Object.keys(newWords).length, "battle lemmas");
